services:
  # Serviço da API FastAPI
  api:
    build:
      context: .              # O contexto é o diretório atual (tech4_feature_api)
      dockerfile: DockerFile  # Aponta para o arquivo no diretório atual
    container_name: fastapi-stock-api
    restart: unless-stopped
    ports:
      - "8000:8000" # Porta da API
    networks:
      - grafana-api-net

  # Serviço do Grafana
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      # Instala o plugin Infinity para conectar à API REST/JSON
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
    networks:
      - grafana-api-net

volumes:
  grafana-data:

networks:
  grafana-api-net:
    driver: bridge
